
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Mar 03 11:24:43 CET 2025
//----------------------------------------------------

package asint;

/** CUP generated interface containing symbol constants. */
public interface ClaseLexica {
  /* terminals */
  public static final int P_ELSE = 36;
  public static final int P_READ = 41;
  public static final int EXPONENTE = 52;
  public static final int PCIERRE = 7;
  public static final int P_FALSE = 31;
  public static final int P_PROC = 34;
  public static final int PORCENTAJE = 46;
  public static final int P_OR = 28;
  public static final int P_IF = 35;
  public static final int AND = 47;
  public static final int P_INT = 24;
  public static final int IGUAL = 16;
  public static final int LT = 10;
  public static final int P_STRING = 32;
  public static final int COMP = 14;
  public static final int DIV = 21;
  public static final int P_NOT = 29;
  public static final int P_AND = 27;
  public static final int GEQ = 13;
  public static final int P_STRUCT = 38;
  public static final int P_WRITE = 42;
  public static final int DIST = 15;
  public static final int EOF = 0;
  public static final int LLAVECIERRE = 9;
  public static final int error = 1;
  public static final int COMA = 48;
  public static final int MUL = 20;
  public static final int FINDECLAR = 23;
  public static final int MENOS = 19;
  public static final int P_NL = 43;
  public static final int P_TYPE = 44;
  public static final int P_NEW = 39;
  public static final int PCOMA = 17;
  public static final int REAL = 4;
  public static final int P_BOOL = 26;
  public static final int P_CALL = 45;
  public static final int ENT = 3;
  public static final int PAP = 6;
  public static final int PUNTO = 51;
  public static final int CORCHETECIERRE = 50;
  public static final int IDEN = 2;
  public static final int P_DELETE = 40;
  public static final int P_TRUE = 30;
  public static final int INIEVAL = 22;
  public static final int LEQ = 11;
  public static final int CORCHETEAP = 49;
  public static final int STRING = 5;
  public static final int P_NULL = 33;
  public static final int LLAVEAP = 8;
  public static final int GT = 12;
  public static final int P_REAL = 25;
  public static final int P_WHILE = 37;
  public static final int MAS = 18;
}

